/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_tritonus_lowlevel_ogg_Page */

#ifndef _Included_org_tritonus_lowlevel_ogg_Page
#define _Included_org_tritonus_lowlevel_ogg_Page
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_tritonus_lowlevel_ogg_Page
 * Method:    malloc
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_tritonus_lowlevel_ogg_Page_malloc
  (JNIEnv *, jobject);

/*
 * Class:     org_tritonus_lowlevel_ogg_Page
 * Method:    free
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_tritonus_lowlevel_ogg_Page_free
  (JNIEnv *, jobject);

/*
 * Class:     org_tritonus_lowlevel_ogg_Page
 * Method:    getVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_tritonus_lowlevel_ogg_Page_getVersion
  (JNIEnv *, jobject);

/*
 * Class:     org_tritonus_lowlevel_ogg_Page
 * Method:    isContinued
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_tritonus_lowlevel_ogg_Page_isContinued
  (JNIEnv *, jobject);

/*
 * Class:     org_tritonus_lowlevel_ogg_Page
 * Method:    getPackets
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_tritonus_lowlevel_ogg_Page_getPackets
  (JNIEnv *, jobject);

/*
 * Class:     org_tritonus_lowlevel_ogg_Page
 * Method:    isBos
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_tritonus_lowlevel_ogg_Page_isBos
  (JNIEnv *, jobject);

/*
 * Class:     org_tritonus_lowlevel_ogg_Page
 * Method:    isEos
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_tritonus_lowlevel_ogg_Page_isEos
  (JNIEnv *, jobject);

/*
 * Class:     org_tritonus_lowlevel_ogg_Page
 * Method:    getGranulePos
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_tritonus_lowlevel_ogg_Page_getGranulePos
  (JNIEnv *, jobject);

/*
 * Class:     org_tritonus_lowlevel_ogg_Page
 * Method:    getSerialNo
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_tritonus_lowlevel_ogg_Page_getSerialNo
  (JNIEnv *, jobject);

/*
 * Class:     org_tritonus_lowlevel_ogg_Page
 * Method:    getPageNo
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_tritonus_lowlevel_ogg_Page_getPageNo
  (JNIEnv *, jobject);

/*
 * Class:     org_tritonus_lowlevel_ogg_Page
 * Method:    setChecksum
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_tritonus_lowlevel_ogg_Page_setChecksum
  (JNIEnv *, jobject);

/*
 * Class:     org_tritonus_lowlevel_ogg_Page
 * Method:    getHeader
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_tritonus_lowlevel_ogg_Page_getHeader
  (JNIEnv *, jobject);

/*
 * Class:     org_tritonus_lowlevel_ogg_Page
 * Method:    getBody
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_tritonus_lowlevel_ogg_Page_getBody
  (JNIEnv *, jobject);

/*
 * Class:     org_tritonus_lowlevel_ogg_Page
 * Method:    setTrace
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_tritonus_lowlevel_ogg_Page_setTrace
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
