/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_tritonus_lowlevel_ogg_Packet */

#ifndef _Included_org_tritonus_lowlevel_ogg_Packet
#define _Included_org_tritonus_lowlevel_ogg_Packet
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_tritonus_lowlevel_ogg_Packet
 * Method:    malloc
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_tritonus_lowlevel_ogg_Packet_malloc
  (JNIEnv *, jobject);

/*
 * Class:     org_tritonus_lowlevel_ogg_Packet
 * Method:    free
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_tritonus_lowlevel_ogg_Packet_free
  (JNIEnv *, jobject);

/*
 * Class:     org_tritonus_lowlevel_ogg_Packet
 * Method:    clear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_tritonus_lowlevel_ogg_Packet_clear
  (JNIEnv *, jobject);

/*
 * Class:     org_tritonus_lowlevel_ogg_Packet
 * Method:    getData
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_tritonus_lowlevel_ogg_Packet_getData
  (JNIEnv *, jobject);

/*
 * Class:     org_tritonus_lowlevel_ogg_Packet
 * Method:    isBos
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_tritonus_lowlevel_ogg_Packet_isBos
  (JNIEnv *, jobject);

/*
 * Class:     org_tritonus_lowlevel_ogg_Packet
 * Method:    isEos
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_tritonus_lowlevel_ogg_Packet_isEos
  (JNIEnv *, jobject);

/*
 * Class:     org_tritonus_lowlevel_ogg_Packet
 * Method:    setTrace
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_tritonus_lowlevel_ogg_Packet_setTrace
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
