/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_tritonus_lowlevel_vorbis_Comment */

#ifndef _Included_org_tritonus_lowlevel_vorbis_Comment
#define _Included_org_tritonus_lowlevel_vorbis_Comment
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_tritonus_lowlevel_vorbis_Comment
 * Method:    malloc
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_tritonus_lowlevel_vorbis_Comment_malloc
  (JNIEnv *, jobject);

/*
 * Class:     org_tritonus_lowlevel_vorbis_Comment
 * Method:    free
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_tritonus_lowlevel_vorbis_Comment_free
  (JNIEnv *, jobject);

/*
 * Class:     org_tritonus_lowlevel_vorbis_Comment
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_tritonus_lowlevel_vorbis_Comment_init
  (JNIEnv *, jobject);

/*
 * Class:     org_tritonus_lowlevel_vorbis_Comment
 * Method:    addComment
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_tritonus_lowlevel_vorbis_Comment_addComment
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_tritonus_lowlevel_vorbis_Comment
 * Method:    addTag
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_tritonus_lowlevel_vorbis_Comment_addTag
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_tritonus_lowlevel_vorbis_Comment
 * Method:    queryCount
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_tritonus_lowlevel_vorbis_Comment_queryCount
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_tritonus_lowlevel_vorbis_Comment
 * Method:    query
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_tritonus_lowlevel_vorbis_Comment_query
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     org_tritonus_lowlevel_vorbis_Comment
 * Method:    getUserComments
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_tritonus_lowlevel_vorbis_Comment_getUserComments
  (JNIEnv *, jobject);

/*
 * Class:     org_tritonus_lowlevel_vorbis_Comment
 * Method:    getVendor
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_tritonus_lowlevel_vorbis_Comment_getVendor
  (JNIEnv *, jobject);

/*
 * Class:     org_tritonus_lowlevel_vorbis_Comment
 * Method:    clear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_tritonus_lowlevel_vorbis_Comment_clear
  (JNIEnv *, jobject);

/*
 * Class:     org_tritonus_lowlevel_vorbis_Comment
 * Method:    setTrace
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_tritonus_lowlevel_vorbis_Comment_setTrace
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
