/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_tritonus_lowlevel_ogg_StreamState */

#ifndef _Included_org_tritonus_lowlevel_ogg_StreamState
#define _Included_org_tritonus_lowlevel_ogg_StreamState
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_tritonus_lowlevel_ogg_StreamState
 * Method:    malloc
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_tritonus_lowlevel_ogg_StreamState_malloc
  (JNIEnv *, jobject);

/*
 * Class:     org_tritonus_lowlevel_ogg_StreamState
 * Method:    free
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_tritonus_lowlevel_ogg_StreamState_free
  (JNIEnv *, jobject);

/*
 * Class:     org_tritonus_lowlevel_ogg_StreamState
 * Method:    init
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_tritonus_lowlevel_ogg_StreamState_init
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_tritonus_lowlevel_ogg_StreamState
 * Method:    clear
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_tritonus_lowlevel_ogg_StreamState_clear
  (JNIEnv *, jobject);

/*
 * Class:     org_tritonus_lowlevel_ogg_StreamState
 * Method:    reset
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_tritonus_lowlevel_ogg_StreamState_reset
  (JNIEnv *, jobject);

/*
 * Class:     org_tritonus_lowlevel_ogg_StreamState
 * Method:    destroy
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_tritonus_lowlevel_ogg_StreamState_destroy
  (JNIEnv *, jobject);

/*
 * Class:     org_tritonus_lowlevel_ogg_StreamState
 * Method:    isEOSReached
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_tritonus_lowlevel_ogg_StreamState_isEOSReached
  (JNIEnv *, jobject);

/*
 * Class:     org_tritonus_lowlevel_ogg_StreamState
 * Method:    packetIn
 * Signature: (Lorg/tritonus/lowlevel/ogg/Packet;)I
 */
JNIEXPORT jint JNICALL Java_org_tritonus_lowlevel_ogg_StreamState_packetIn
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_tritonus_lowlevel_ogg_StreamState
 * Method:    pageOut
 * Signature: (Lorg/tritonus/lowlevel/ogg/Page;)I
 */
JNIEXPORT jint JNICALL Java_org_tritonus_lowlevel_ogg_StreamState_pageOut
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_tritonus_lowlevel_ogg_StreamState
 * Method:    flush
 * Signature: (Lorg/tritonus/lowlevel/ogg/Page;)I
 */
JNIEXPORT jint JNICALL Java_org_tritonus_lowlevel_ogg_StreamState_flush
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_tritonus_lowlevel_ogg_StreamState
 * Method:    pageIn
 * Signature: (Lorg/tritonus/lowlevel/ogg/Page;)I
 */
JNIEXPORT jint JNICALL Java_org_tritonus_lowlevel_ogg_StreamState_pageIn
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_tritonus_lowlevel_ogg_StreamState
 * Method:    packetOut
 * Signature: (Lorg/tritonus/lowlevel/ogg/Packet;)I
 */
JNIEXPORT jint JNICALL Java_org_tritonus_lowlevel_ogg_StreamState_packetOut
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_tritonus_lowlevel_ogg_StreamState
 * Method:    packetPeek
 * Signature: (Lorg/tritonus/lowlevel/ogg/Packet;)I
 */
JNIEXPORT jint JNICALL Java_org_tritonus_lowlevel_ogg_StreamState_packetPeek
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_tritonus_lowlevel_ogg_StreamState
 * Method:    setTrace
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_tritonus_lowlevel_ogg_StreamState_setTrace
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
