/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_tritonus_lowlevel_vorbis_Info */

#ifndef _Included_org_tritonus_lowlevel_vorbis_Info
#define _Included_org_tritonus_lowlevel_vorbis_Info
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_tritonus_lowlevel_vorbis_Info
 * Method:    malloc
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_tritonus_lowlevel_vorbis_Info_malloc
  (JNIEnv *, jobject);

/*
 * Class:     org_tritonus_lowlevel_vorbis_Info
 * Method:    free
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_tritonus_lowlevel_vorbis_Info_free
  (JNIEnv *, jobject);

/*
 * Class:     org_tritonus_lowlevel_vorbis_Info
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_tritonus_lowlevel_vorbis_Info_init
  (JNIEnv *, jobject);

/*
 * Class:     org_tritonus_lowlevel_vorbis_Info
 * Method:    clear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_tritonus_lowlevel_vorbis_Info_clear
  (JNIEnv *, jobject);

/*
 * Class:     org_tritonus_lowlevel_vorbis_Info
 * Method:    getChannels
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_tritonus_lowlevel_vorbis_Info_getChannels
  (JNIEnv *, jobject);

/*
 * Class:     org_tritonus_lowlevel_vorbis_Info
 * Method:    getRate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_tritonus_lowlevel_vorbis_Info_getRate
  (JNIEnv *, jobject);

/*
 * Class:     org_tritonus_lowlevel_vorbis_Info
 * Method:    encodeInit
 * Signature: (IIIII)I
 */
JNIEXPORT jint JNICALL Java_org_tritonus_lowlevel_vorbis_Info_encodeInit
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     org_tritonus_lowlevel_vorbis_Info
 * Method:    encodeInitVBR
 * Signature: (IIF)I
 */
JNIEXPORT jint JNICALL Java_org_tritonus_lowlevel_vorbis_Info_encodeInitVBR
  (JNIEnv *, jobject, jint, jint, jfloat);

/*
 * Class:     org_tritonus_lowlevel_vorbis_Info
 * Method:    headerIn
 * Signature: (Lorg/tritonus/lowlevel/vorbis/Comment;Lorg/tritonus/lowlevel/ogg/Packet;)I
 */
JNIEXPORT jint JNICALL Java_org_tritonus_lowlevel_vorbis_Info_headerIn
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     org_tritonus_lowlevel_vorbis_Info
 * Method:    setTrace
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_tritonus_lowlevel_vorbis_Info_setTrace
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
