/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_tritonus_lowlevel_ogg_Buffer */

#ifndef _Included_org_tritonus_lowlevel_ogg_Buffer
#define _Included_org_tritonus_lowlevel_ogg_Buffer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_tritonus_lowlevel_ogg_Buffer
 * Method:    malloc
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_tritonus_lowlevel_ogg_Buffer_malloc
  (JNIEnv *, jobject);

/*
 * Class:     org_tritonus_lowlevel_ogg_Buffer
 * Method:    free
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_tritonus_lowlevel_ogg_Buffer_free
  (JNIEnv *, jobject);

/*
 * Class:     org_tritonus_lowlevel_ogg_Buffer
 * Method:    writeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_tritonus_lowlevel_ogg_Buffer_writeInit
  (JNIEnv *, jobject);

/*
 * Class:     org_tritonus_lowlevel_ogg_Buffer
 * Method:    writeTrunc
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_tritonus_lowlevel_ogg_Buffer_writeTrunc
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_tritonus_lowlevel_ogg_Buffer
 * Method:    writeAlign
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_tritonus_lowlevel_ogg_Buffer_writeAlign
  (JNIEnv *, jobject);

/*
 * Class:     org_tritonus_lowlevel_ogg_Buffer
 * Method:    writeCopy
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_org_tritonus_lowlevel_ogg_Buffer_writeCopy
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     org_tritonus_lowlevel_ogg_Buffer
 * Method:    reset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_tritonus_lowlevel_ogg_Buffer_reset
  (JNIEnv *, jobject);

/*
 * Class:     org_tritonus_lowlevel_ogg_Buffer
 * Method:    writeClear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_tritonus_lowlevel_ogg_Buffer_writeClear
  (JNIEnv *, jobject);

/*
 * Class:     org_tritonus_lowlevel_ogg_Buffer
 * Method:    readInit
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_org_tritonus_lowlevel_ogg_Buffer_readInit
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     org_tritonus_lowlevel_ogg_Buffer
 * Method:    write
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_tritonus_lowlevel_ogg_Buffer_write
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_tritonus_lowlevel_ogg_Buffer
 * Method:    look
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_tritonus_lowlevel_ogg_Buffer_look
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_tritonus_lowlevel_ogg_Buffer
 * Method:    look1
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_tritonus_lowlevel_ogg_Buffer_look1
  (JNIEnv *, jobject);

/*
 * Class:     org_tritonus_lowlevel_ogg_Buffer
 * Method:    adv
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_tritonus_lowlevel_ogg_Buffer_adv
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_tritonus_lowlevel_ogg_Buffer
 * Method:    adv1
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_tritonus_lowlevel_ogg_Buffer_adv1
  (JNIEnv *, jobject);

/*
 * Class:     org_tritonus_lowlevel_ogg_Buffer
 * Method:    read
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_tritonus_lowlevel_ogg_Buffer_read
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_tritonus_lowlevel_ogg_Buffer
 * Method:    read1
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_tritonus_lowlevel_ogg_Buffer_read1
  (JNIEnv *, jobject);

/*
 * Class:     org_tritonus_lowlevel_ogg_Buffer
 * Method:    bytes
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_tritonus_lowlevel_ogg_Buffer_bytes
  (JNIEnv *, jobject);

/*
 * Class:     org_tritonus_lowlevel_ogg_Buffer
 * Method:    bits
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_tritonus_lowlevel_ogg_Buffer_bits
  (JNIEnv *, jobject);

/*
 * Class:     org_tritonus_lowlevel_ogg_Buffer
 * Method:    getBuffer
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_tritonus_lowlevel_ogg_Buffer_getBuffer
  (JNIEnv *, jobject);

/*
 * Class:     org_tritonus_lowlevel_ogg_Buffer
 * Method:    setTrace
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_tritonus_lowlevel_ogg_Buffer_setTrace
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
