/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_tritonus_lowlevel_vorbis_DspState */

#ifndef _Included_org_tritonus_lowlevel_vorbis_DspState
#define _Included_org_tritonus_lowlevel_vorbis_DspState
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_tritonus_lowlevel_vorbis_DspState
 * Method:    malloc
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_tritonus_lowlevel_vorbis_DspState_malloc
  (JNIEnv *, jobject);

/*
 * Class:     org_tritonus_lowlevel_vorbis_DspState
 * Method:    free
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_tritonus_lowlevel_vorbis_DspState_free
  (JNIEnv *, jobject);

/*
 * Class:     org_tritonus_lowlevel_vorbis_DspState
 * Method:    initAnalysis
 * Signature: (Lorg/tritonus/lowlevel/vorbis/Info;)I
 */
JNIEXPORT jint JNICALL Java_org_tritonus_lowlevel_vorbis_DspState_initAnalysis
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_tritonus_lowlevel_vorbis_DspState
 * Method:    headerOut
 * Signature: (Lorg/tritonus/lowlevel/vorbis/Comment;Lorg/tritonus/lowlevel/ogg/Packet;Lorg/tritonus/lowlevel/ogg/Packet;Lorg/tritonus/lowlevel/ogg/Packet;)I
 */
JNIEXPORT jint JNICALL Java_org_tritonus_lowlevel_vorbis_DspState_headerOut
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     org_tritonus_lowlevel_vorbis_DspState
 * Method:    write
 * Signature: ([[FI)I
 */
JNIEXPORT jint JNICALL Java_org_tritonus_lowlevel_vorbis_DspState_write
  (JNIEnv *, jobject, jobjectArray, jint);

/*
 * Class:     org_tritonus_lowlevel_vorbis_DspState
 * Method:    blockOut
 * Signature: (Lorg/tritonus/lowlevel/vorbis/Block;)I
 */
JNIEXPORT jint JNICALL Java_org_tritonus_lowlevel_vorbis_DspState_blockOut
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_tritonus_lowlevel_vorbis_DspState
 * Method:    flushPacket
 * Signature: (Lorg/tritonus/lowlevel/ogg/Packet;)I
 */
JNIEXPORT jint JNICALL Java_org_tritonus_lowlevel_vorbis_DspState_flushPacket
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_tritonus_lowlevel_vorbis_DspState
 * Method:    initSynthesis
 * Signature: (Lorg/tritonus/lowlevel/vorbis/Info;)I
 */
JNIEXPORT jint JNICALL Java_org_tritonus_lowlevel_vorbis_DspState_initSynthesis
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_tritonus_lowlevel_vorbis_DspState
 * Method:    blockIn
 * Signature: (Lorg/tritonus/lowlevel/vorbis/Block;)I
 */
JNIEXPORT jint JNICALL Java_org_tritonus_lowlevel_vorbis_DspState_blockIn
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_tritonus_lowlevel_vorbis_DspState
 * Method:    pcmOut
 * Signature: ([[F)I
 */
JNIEXPORT jint JNICALL Java_org_tritonus_lowlevel_vorbis_DspState_pcmOut
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     org_tritonus_lowlevel_vorbis_DspState
 * Method:    read
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_tritonus_lowlevel_vorbis_DspState_read
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_tritonus_lowlevel_vorbis_DspState
 * Method:    getSequence
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_tritonus_lowlevel_vorbis_DspState_getSequence
  (JNIEnv *, jobject);

/*
 * Class:     org_tritonus_lowlevel_vorbis_DspState
 * Method:    clear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_tritonus_lowlevel_vorbis_DspState_clear
  (JNIEnv *, jobject);

/*
 * Class:     org_tritonus_lowlevel_vorbis_DspState
 * Method:    setTrace
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_tritonus_lowlevel_vorbis_DspState_setTrace
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
