name: Compile and package
on: [push]
jobs:
  CompipleAndPackage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Jlayer Download
        uses: nvoxland/jar-download-action@v1.0.0
        with:
          groupId: javazoom
          artifactId: jlayer
          version: 1.0.1
          outputDirectory: ~/.ant/lib

      - name: Prepare env
        run: |
          autoconf
          ./configure
          ant -f build-dtd.xml          

      - name: Build packages
        run: ant

      - name: Build vorbis
        run: make -C src/lib/vorbis

      - name: Build lame
        run: make -C src/lib/lame
