name: Compile and package
on: [push]
permissions:
  contents: write
  packages: write
jobs:
  CompipleAndPackage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Jlayer Download
        uses: nvoxland/jar-download-action@v1.0.0
        with:
          groupId: javazoom
          artifactId: jlayer
          version: 1.0.1
          outputDirectory: .ant/lib

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Prepare env
        run: |
          sudo mv .ant $HOME
          sudo apt-get install -y libogg-dev libvorbis-dev libmp3lame-dev
          autoconf
          ./configure
          ant -f build-dtd.xml          

      - name: Build packages
        run: ant

      - name: Build vorbis
        run: | 
          make -C src/lib/vorbis
          zip libtritonusvorbis.zip src/lib/vorbis/libtritonusvorbis.so*

      - name: Build lame
        run: |
          make -C src/lib/lame
          zip liblametritonus.zip src/lib/lame/liblametritonus.so*         

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            libtritonusvorbis.zip
            liblametritonus.zip

      - name: Deploy maven
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILES: 'tritonus_dsp,tritonus_mp3,tritonus_remaining,tritonus_share,tritonus_vorbis'
        run: |
          IFS="," read -a files <<< ${{ env.FILES }}
          for i in "${files[@]}"; do
            mvn deploy:deploy-file -Durl=https://maven.pkg.github.com/marcelopio/tritonus-all -DrepositoryId=github -Dfile=dist/${i}-0.3.8_beta01.jar -DartifactId=${i} -DgroupId=org.tritonus -Dversion=0.3.8_beta1 -Dpackaging=jar -DgeneratePom=true  
          done
